In [ ]:
import sys
import os

# Get the directory containing the notebook
NOTEBOOK_DIR = os.getcwd()

# Compute project root (go up one level)
PROJECT_ROOT = os.path.abspath(os.path.join(NOTEBOOK_DIR, '..'))

# Add project root to path
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

print(sys.path)

In [1]:
import scanpy as sc

In [3]:
liver_feed_path = "/Users/jeromecho/Library/CloudStorage/OneDrive-Personal/Thesis/data/liver/complex/liver_feed.loom"
adata = sc.read_loom(liver_feed_path)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

In [4]:
adata

AnnData object with n_obs × n_vars = 18715 × 32285
    obs: 'RNA_snn_res.0.8', 'cent1', 'nCount_RNA', 'nFeature_RNA', 'orig.ident', 'percent.mt', 'port1', 'seurat_clusters', 'time'

In [5]:
adata.obs

,RNA_snn_res.0.8,cent1,nCount_RNA,nFeature_RNA,orig.ident,percent.mt,port1,seurat_clusters,time
CellID,,,,,,,,,
AAACCCAAGAGGCGGA-1,15,0.828937,1801.0,754,1,13.770128,-0.069600,15,1
AAACCCAAGGCCTAGA-1,15,0.777387,3511.0,1431,1,9.569923,-0.102473,15,1
AAACCCAGTCATAGTC-1,9,0.676476,9154.0,2717,1,14.026655,-0.084608,9,1
AAACCCAGTGCCTACG-1,9,1.008451,4524.0,1860,1,3.558798,-0.355235,9,1
AAACCCATCTTTCCGG-1,8,0.008513,3426.0,1278,1,13.164040,0.305015,8,1
...,...,...,...,...,...,...,...,...,...
TTTGATCCAACCCGCA-5,4,-0.120515,20196.0,3930,1,16.364627,0.346997,4,5
TTTGATCCATTGACTG-5,4,-0.227613,17039.0,3721,1,12.952638,0.277530,4,5
TTTGGAGGTCTTAGTG-5,4,-0.239695,13689.0,3369,1,6.815691,0.434825,4,5
TTTGGTTGTACAGGTG-5,4,-0.169918,9741.0,2544,1,12.719433,0.189427,4,5
TTTGTTGGTCCAGTTA-5,4,-0.093560,16957.0,3576,1,15.126496,0.494806,4,5

In [6]:
adata.var

Empty DataFrame
Columns: []
Index: [Xkr4, Gm1992, Gm19938, Gm37381, Rp1, Sox17, Gm37587, Gm37323, Mrpl15, Lypla1, Tcea1, Rgs20, Gm16041, Atp6v1h, Oprk1, Npbwr1, Rb1cc1, 4732440D04Rik, Alkal1, St18, Pcmtd1, Gm26901, Gm30414, Sntg1, Rrs1, Adhfe1, 2610203C22Rik, Vxn, Gm29520, Mybl1, Vcpip1, 1700034P13Rik, Sgk3, Mcmdc2, Snhg6, Tcf24, Ppp1r42, Gm15818, Cops5, Cspp1, Arfgef1, Cpa6, Prex2, A830018L16Rik, Gm17644, Gm29663, Sulf1, Slco5a1, Gm29283, Prdm14, Ncoa2, Gm29570, Tram1, Lactb2, Xkr9, Eya1, Gm9947, Msc, Trpa1, Kcnb2, Terf1, Sbspon, 4930444P10Rik, Rpl7, Rdh10, Gm28095, Stau2, Gm7568, Ube2w, Eloc, D030040B21Rik, Tmem70, Ly96, Gm28376, Jph1, Gm28783, Gdap1, Gm28784, Pi15, Gm28154, Gm16070, Crispld1, Gm28153, Gm28756, Crisp4, Defb18, Defb41, Gm15825, Tfap2d, Tfap2b, Gm28340, Pkhd1, 4930486I03Rik, Gm28653, Il17a, Il17f, Mcm3, Gm28065, 6720483E21Rik, Paqr8, ...]

[32285 rows x 0 columns]